/**
 * Auto-generates docs/RULES.md from src/validator/rules/. Run:
 *
 *   pnpm exec tsx scripts/gen-rules-doc.ts
 *
 * The CI runs this and fails if the file is out of sync — keeps the rule
 * catalog page accurate without anyone remembering to update it manually.
 */

import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { ALL_RULES } from "../src/validator/rules/index.js";
import type { Rule } from "../src/validator/types.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, "..", "docs", "RULES.md");
const BASE_DOC_URL = "https://razorpay.com/docs";

function severityBadge(s: string): string {
  if (s === "error") return "🔴 error";
  if (s === "warning") return "🟡 warning";
  return "🔵 info";
}

function renderRule(rule: Rule): string {
  const langs = rule.languages.includes("*") ? "all SDKs" : [...rule.languages].join(", ");
  const url = `${BASE_DOC_URL}/${rule.citation.route}/${rule.citation.section !== undefined ? `#${rule.citation.section}` : ""}`;
  return [
    `### ${rule.id} — ${rule.title}`,
    "",
    `**Severity:** ${severityBadge(rule.severity)} · **Concern:** \`${rule.concern}\` · **Languages:** ${langs} · **Detector:** \`${rule.detector.kind}\``,
    "",
    `${rule.fix.explanation}`,
    "",
    "**Fix:**",
    "",
    "```",
    rule.fix.correctPattern,
    "```",
    "",
    `**Citation:** [\`${rule.citation.route}\`](${url}) — ${rule.citation.excerpt}`,
    "",
  ].join("\n");
}

function render(): string {
  const byConcern = new Map<string, Rule[]>();
  for (const r of ALL_RULES) {
    const list = byConcern.get(r.concern) ?? [];
    list.push(r);
    byConcern.set(r.concern, list);
  }

  const concerns = [...byConcern.keys()].sort();
  const lines: string[] = [
    "<!-- AUTO-GENERATED by scripts/gen-rules-doc.ts. Do not edit by hand. -->",
    "",
    "# Validation rule catalog",
    "",
    `${ALL_RULES.length} hand-curated rules. Each fires on a known Razorpay integration mistake and points at the canonical doc that explains the fix. Severity \`error\` means we're confident; \`warning\` means likely-bug; \`info\` is "you might want to know."`,
    "",
    "Run:",
    "",
    "```bash",
    "validate_razorpay_code(code, language?, concern?)",
    "```",
    "",
    "Or from a code snippet via your MCP-aware editor.",
    "",
    "## Rules by concern",
    "",
  ];

  for (const concern of concerns) {
    const rules = byConcern.get(concern) ?? [];
    rules.sort((a, b) => a.id.localeCompare(b.id));
    lines.push(`## \`${concern}\` (${rules.length} rule${rules.length === 1 ? "" : "s"})`);
    lines.push("");
    for (const r of rules) lines.push(renderRule(r));
  }

  return lines.join("\n");
}

writeFileSync(OUT, render());
process.stdout.write(`wrote ${OUT}\n`);
